### PR TITLE
chore: add test for `SaveUserOrgUnitUseCase`

### PR DESCRIPTION
**Pull request by delemaf**
### :pushpin: References

-   **Issue:** https://app.clickup.com/t/8694ekvck
- 8694ekvck

### :memo: Implementation

- `ts-mockito` installed
- test on `SaveUserOrgUnitUseCase`

### :fire: Testing

To launch the specific test `yarn test SaveUserOrgUnitUseCase.spec.ts`

### CODE REVIEW

**Comment by delemaf** [comment]
I didn't understand why we overwrite org unit `name` and `path`, is it a normal behaviour? @eperedo 

Example:
I wanted to replace user's org units with this org unit : 
`{
        id: "ImspTQPwCqd",
        name: "Sierra Leone",
        path: ["ImspTQPwCqd"],
 }`
When I look what's saved in users I've :
`{
        id: "ImspTQPwCqd",
        name: "",
        path: [],
 }`

**Review by eperedo — APPROVED** [review]
Looks good, thanks @delemaf!

**Comment by eperedo** [comment]
@delemaf that was because the org. unit selector component only returns the id of the selected orgunits and to avoid making an extra request for orgunits we're just sending the ids. This is not a bug because if you want to save the orgunits for a user DHIS only needs the ids: 

image

It could be an improvement to get the full information of the org. units but not necessary for this particular feature.

**Comment by delemaf** [comment]
> @delemaf that was because the org. unit selector component only returns the id of the selected orgunits and to avoid making an extra request for orgunits we're just sending the ids. This is not a bug because if you want to save the orgunits for a user DHIS only needs the ids:
> 
> image
> 
> It could be an improvement to get the full information of the org. units but not necessary for this particular feature.

Alright I understand, I just wanted to be sure it doesn't erase org units name 👌

**Pull request merged**
