### PR TITLE
update i18n imports on edit page

### PR DESCRIPTION
**Pull request by eperedo**
### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/86944c81y

### :memo: Implementation

- [x] fix imports on edit user page

### :video_camera: Screenshots/Screen capture

image

### CODE REVIEW

**Comment by tokland** [comment]
I am a bit confused about this one. I set Spanish as keyUiLocale, but I still see everything in English. When checking `i18n.store.data.es`, there are only translations for feedback-component. I tried to upload "@dhis2/d2-i18n": "1.1.3" in the app, still the same.

**Comment by eperedo** [comment]
@tokland development and installed app works for me. I've tried to replicate what you mention but without no luck.

image
image

**Comment by tokland** [comment]
I built the zip and uploaded to our who-dev-238

https://dev.eyeseetea.com/who-dev-238/api/apps/User-Extended-App/index.html
(username: dev.user -> ui language = ES)

I see that the some literals are translated (ie, the filter: "Filtros avanzados"), but most of the table is not. If you build and upload the zip there, you see different results?

**Review by tokland — COMMENTED** [review]
I left that as standalone comment, copying as review for a better workflow:

I built the zip and uploaded to our who-dev-238

https://dev.eyeseetea.com/who-dev-238/api/apps/User-Extended-App/index.html
(username: dev.user -> Interface language = ES)

I see that the some literals are translated (ie, the filter button: "Filtros avanzados"), but the rest is not.

**Comment by MiquelAdell** [comment]
Just checking…
I don't have access to the original task so I guess this is a task from @adrianq ?
I guess @tokland 's comment from 3 weeks ago is not addressed?

**Comment by eperedo** [comment]
This is a weird problem we still have with translations. Arnau is creating a build from this branch and not all the translations are working properly. However I cannot replicate the bug because for me it's working without any problems (in my local and the dev environment).

Screenshots from dev
image

image

**Comment by tokland** [comment]
It may be something particular in my build. In any case, as this PR does not affect this, it can be merged. 

If some build of yours also messes the translations, then we can look up this again.

**Pull request merged**
